---
title: "ShinyProjectWrangling"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(dplyr)
```

```{r}
path_in <- "C:/Users/abran/OneDrive/Documents/STAT 231 - Data Science/git/Shiny-PowerPUG-Girls"
sat <- read_csv(paste0(path_in,"/2012_SAT_Results.csv"))
feedback <- read_csv(paste0(path_in,"/2012_20NYC_20School_20Survey.csv"))

data <- inner_join(sat, feedback, by = "DBN")
```

```{r}
data2 <- data %>% 
  janitor::clean_names() %>% 
  filter(num_of_sat_test_takers != "s") %>% 
  mutate(school_type = as.factor(school_type),
         school_name_2 = as.factor(school_name_2),
         n_test_takers = as.numeric(num_of_sat_test_takers),
         reading = as.numeric(sat_critical_reading_avg_score),
         math = as.numeric(sat_math_avg_score),
         writing = as.numeric(sat_writing_avg_score),
         parent_response_rate = as.numeric(total_parent_response_rate_percent),
         teacher_response_rate = as.numeric(total_teacher_response_rate_percent),
         student_response_rate = as.numeric(total_student_response_rate_percent),
         academic_expectations = as.numeric(total_academic_expectations_score),
         communication = as.numeric(total_communication_score),
         engagement = as.numeric(total_engagement_score),
         safety_and_respect = as.numeric(total_safety_and_respect_score),
         SAT_score = reading + math + writing, 
         total_satisfaction = (academic_expectations + communication + 
           engagement + safety_and_respect) / 4
         ) %>% 
  select(-c(school_name, num_of_sat_test_takers, sat_critical_reading_avg_score, 
            sat_math_avg_score, sat_writing_avg_score, total_parent_response_rate_percent, 
            total_teacher_response_rate_percent, total_student_response_rate_percent, 
            total_academic_expectations_score, total_communication_score, total_engagement_score,
            total_safety_and_respect_score)) %>% 
  mutate(school_name = school_name_2) %>% 
  select(-school_name_2)
  

# School Type:
  # HS, MS/HS, ES/MS/HS
  # HST: Transfer High School
  # YABC: Young Adult Borough Center
  # D75: District 75, Special Education

```

```{r}
out_path <- "C:/Users/abran/OneDrive/Documents/STAT 231 - Data Science/git/Shiny-PowerPUG-Girls"

write_csv(x = data2, path = paste0(out_path,"/shiny_project_data.csv"))
```

